# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('filetype', models.CharField(choices=[('SVG', 'svg'), ('PNG', 'png')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='LogoTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='logoentries',
            name='tags',
            field=models.ManyToManyField(to='logocdn.LogoTags'),
        ),
    ]
