# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-03 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logocdn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoentries',
            name='filetype',
        ),
        migrations.AddField(
            model_name='logoentries',
            name='file_type',
            field=models.CharField(choices=[('SVG', 'svg'), ('PNG', 'png'), ('BMP', 'bmp'), ('JPG', 'jpg')], default='SVG', max_length=16),
            preserve_default=False,
        ),
    ]
