# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-03 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logocdn', '0002_auto_20181003_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logoentries',
            old_name='name',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='logoentries',
            name='display_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='logoentries',
            name='short_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='logoentries',
            name='file_type',
            field=models.CharField(blank=True, choices=[('SVG', 'svg'), ('PNG', 'png'), ('BMP', 'bmp'), ('JPG', 'jpg')], max_length=16, null=True),
        ),
    ]
