# Generated by Django 2.1.11 on 2019-09-16 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSAppRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Identifier for the cmsapp. By convention its the module name.', max_length=128, null=True, unique=True)),
                ('module_name', models.CharField(help_text='The module name for the cmsapp.', max_length=128, null=True)),
                ('display_name', models.CharField(help_text='Pretty name to display in lists and admin interfaces.', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMSArchivesIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=1975)),
            ],
        ),
        migrations.CreateModel(
            name='CMSCharField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CMSContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField(default='Empty', max_length=20480)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('meta_description', models.TextField(blank=True, default='', max_length=20480)),
                ('page', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CMSEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=1024)),
                ('slug', models.SlugField(max_length=1024, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('frontpage', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('lists_include', models.BooleanField(default=True)),
                ('page_number', models.IntegerField(default=1)),
                ('logo_url', models.CharField(blank=True, default='/static/mycms/images/png/default.png', max_length=1024, null=True)),
                ('content', models.ManyToManyField(blank=True, to='mycms.CMSContents')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CMSMarkUps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.CharField(default='Creole', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CMSNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, null=True)),
                ('slug', models.SlugField(max_length=64)),
                ('path', models.CharField(db_index=True, help_text='Path to the node. example: /cms/category/file', max_length=2000, unique=True)),
                ('cmsapp', models.ForeignKey(help_text='Foreignkey to the cmsapp', on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.CMSAppRegistry')),
                ('parent', models.ForeignKey(blank=True, help_text=' A foreinkey to the parent path.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parentpath', to='mycms.CMSNode')),
            ],
        ),
        migrations.CreateModel(
            name='CMSPageTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(default='DefaultType', max_length=64)),
                ('text', models.CharField(default='default class', max_length=128)),
                ('view_class', models.CharField(default='DefaultView', max_length=256)),
                ('view_template', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CMSPaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2000, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.CMSPaths')),
            ],
        ),
        migrations.CreateModel(
            name='CMSTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NotSet', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CMSTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='page.html', max_length=1024)),
                ('template', models.TextField(default='empty template', max_length=10240)),
            ],
        ),
        migrations.CreateModel(
            name='CMSTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='no content')),
            ],
        ),
        migrations.AddField(
            model_name='cmsentries',
            name='page_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.CMSPageTypes'),
        ),
        migrations.AddField(
            model_name='cmsentries',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.CMSPaths'),
        ),
        migrations.AddField(
            model_name='cmsentries',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.CMSTemplates'),
        ),
        migrations.AddField(
            model_name='cmscontents',
            name='markup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mycms.CMSMarkUps'),
        ),
        migrations.AddField(
            model_name='cmscontents',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mycms.CMSTags'),
        ),
        migrations.AddField(
            model_name='cmsarchivesindex',
            name='entries',
            field=models.ManyToManyField(blank=True, to='mycms.CMSEntries'),
        ),
    ]
