# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cmscontents',
            table='yacms_cmscontents',
        ),
        migrations.AlterModelTable(
            name='cmsentries',
            table='yacms_cmsentries',
        ),
        migrations.AlterModelTable(
            name='cmsmarkups',
            table='yacms_cmsmarkups',
        ),
        migrations.AlterModelTable(
            name='cmspagetypes',
            table='yacms_cmspagetypes',
        ),
        migrations.AlterModelTable(
            name='cmspaths',
            table='yacms_cmspaths',
        ),
        migrations.AlterModelTable(
            name='cmstags',
            table='yacms_cmstags',
        ),
        migrations.AlterModelTable(
            name='cmstemplates',
            table='yacms_cmstemplates',
        ),
    ]
