# Generated by Django 2.2.6.dev20190909114231 on 2019-09-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsappregistry',
            name='base_url',
            field=models.CharField(default='/cms', max_length=16),
        ),
        migrations.AddField(
            model_name='cmscharfield',
            name='text',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
