# Generated by Django 2.2.6.dev20190909114231 on 2019-10-14 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0002_auto_20191014_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='page_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mycms.PageType'),
        ),
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mycms.Node'),
        ),
    ]
