# Generated by Django 2.2.6.dev20190909114231 on 2019-10-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycms', '0003_cmsmodeltextfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsmodelfield',
            old_name='name',
            new_name='cmsmodelfield_name_9824',
        ),
        migrations.RenameField(
            model_name='cmsmodelfield',
            old_name='node',
            new_name='cmsmodelfield_node_9824',
        ),
    ]
