# Generated by Django 2.2.6.dev20190909114231 on 2019-10-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mycms", "0004_auto_20191020_2233")]

    operations = [
        migrations.CreateModel(
            name="Templates",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="node",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mycms.Templates",
            ),
        ),
    ]
