# Generated by Django 2.2.6.dev20190909114231 on 2019-10-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("mycms", "0005_auto_20191022_2121")]

    operations = [migrations.RenameModel(old_name="Templates", new_name="Template")]
