# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('yacms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsentries',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 8, 19, 55, 56, 253591, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
