# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yacms', '0002_cmsentries_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmscontents',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cmsentries',
            name='content',
            field=models.ManyToManyField(blank=True, to='yacms.CMSContents'),
        ),
    ]
