# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yacms', '0003_auto_20160312_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmscontents',
            name='title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
