# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yacms', '0004_cmscontents_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsentries',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cmsentries',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
